import '@/styles/globals.css'
import '@radix-ui/themes/styles.css';
import Link from 'next/link'
import { Button, Flex, Theme, ThemePanel } from '@radix-ui/themes';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Header(){
  return(
    <>
      <Flex gap="7"p="5" className='border-b border-white'>
        <Link href="/" replace>       
          <Button variant='ghost' size='4'>Portfolio</Button>
        </Link>
        <Link href="orders" replace>       
          <Button variant='ghost' size='4'>Orders</Button>
        </Link>
      </Flex>
    </>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='min-h-screen flex flex-col'>
      <Theme appearance="dark" accentColor="jade" grayColor="sand">  
        {/* <ThemePanel/>         */}
        <Header/>
          {children}
        </Theme>
      </body>
    </html>
  )
}
