import '@/styles/globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Header(){
  return(
    <>
      <div className='flex p-4 gap-4 bg-slate-300'>
        <Link href="/" replace>
          <div>
            Home
          </div>
        </Link>
        <Link href="orders" replace>
          <div>
            Orders
          </div>
        </Link>
      </div>
    </>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen flex flex-col'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
